'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {parseFilterRules,matchFilterRules,cosmeticSelectorsForHost,applyRemoveParamRules}=require('../src/core/filter-rules');
test('resource type and third-party options',()=>{const r=parseFilterRules('||ads.example^$script,third-party');assert.equal(matchFilterRules('https://ads.example/a.js',r,{topUrl:'https://site.test/',resourceType:'script'}),'block');assert.equal(matchFilterRules('https://ads.example/a.png',r,{topUrl:'https://site.test/',resourceType:'image'}),null);});
test('domain option scopes filters',()=>{const r=parseFilterRules('||ads.example^$domain=news.test|~shop.news.test');assert.equal(matchFilterRules('https://ads.example/a',r,{topUrl:'https://news.test/',resourceType:'image'}),'block');assert.equal(matchFilterRules('https://ads.example/a',r,{topUrl:'https://shop.news.test/',resourceType:'image'}),null);});
test('important overrides exception',()=>{const r=parseFilterRules('||ads.example^$important\n@@||ads.example^');assert.equal(matchFilterRules('https://ads.example/x',r,{topUrl:'https://site.test/',resourceType:'script'}),'block');});
test('cosmetic scope honors exceptions',()=>{const r=parseFilterRules('news.test##.ad\nshop.test##.promo\nnews.test#@#.ad');assert.deepEqual(cosmeticSelectorsForHost('news.test',r),[]);assert.deepEqual(cosmeticSelectorsForHost('shop.test',r),['.promo']);});
test('removeparam strips query key',()=>{const r=parseFilterRules('||example.test^$removeparam=utm_source');const out=applyRemoveParamRules('https://example.test/a?utm_source=x&id=2',r,{topUrl:'https://site.test/'});assert.equal(new URL(out).searchParams.has('utm_source'),false);assert.equal(new URL(out).searchParams.get('id'),'2');});


test('removeparam rules rewrite URLs without becoming request blockers',()=>{const r=parseFilterRules('||duckduckgo.com^$removeparam=t');const url='https://duckduckgo.com/?q=privacy%20badger';assert.equal(matchFilterRules(url,r,{topUrl:url,resourceType:'mainFrame'}),null);const withTracking='https://duckduckgo.com/?q=privacy%20badger&t=aegis';const out=applyRemoveParamRules(withTracking,r,{topUrl:withTracking,resourceType:'mainFrame'});assert.equal(new URL(out).searchParams.get('q'),'privacy badger');assert.equal(new URL(out).searchParams.has('t'),false);});
test('removeparam exceptions preserve opted-out parameters',()=>{const r=parseFilterRules('||example.test^$removeparam=utm_source\n@@||example.test/safe^$removeparam=utm_source');const blocked=applyRemoveParamRules('https://example.test/page?utm_source=x&id=1',r,{topUrl:'https://example.test/page',resourceType:'mainFrame'});assert.equal(new URL(blocked).searchParams.has('utm_source'),false);const safe=applyRemoveParamRules('https://example.test/safe?utm_source=x&id=1',r,{topUrl:'https://example.test/safe',resourceType:'mainFrame'});assert.equal(new URL(safe).searchParams.get('utm_source'),'x');});
test('generic filter-list rules do not cancel top-level navigation unless document-scoped',()=>{const generic=parseFilterRules('||duckduckgo.com^');const url='https://duckduckgo.com/?q=privacy%20badger';assert.equal(matchFilterRules(url,generic,{topUrl:url,resourceType:'mainFrame'}),null);const explicit=parseFilterRules('||blocked.example^$document');assert.equal(matchFilterRules('https://blocked.example/',explicit,{topUrl:'https://blocked.example/',resourceType:'mainFrame'}),'block');});
test('unsupported action modifiers fail open instead of widening into blockers',()=>{const r=parseFilterRules('||cdn.example^$redirect=noopjs\n||site.example^$csp=script-src-none');assert.equal(matchFilterRules('https://cdn.example/app.js',r,{topUrl:'https://news.example/',resourceType:'script'}),null);assert.equal(matchFilterRules('https://site.example/api',r,{topUrl:'https://news.example/',resourceType:'xhr'}),null);});
