'use strict';
const TYPE_MAP=Object.freeze({script:'script',image:'image',stylesheet:'stylesheet',font:'font',media:'media',xmlhttprequest:'xhr',xhr:'xhr',frame:'subFrame',subdocument:'subFrame',document:'mainFrame',doc:'mainFrame',ping:'ping',websocket:'webSocket',popup:'popup',other:'other'});
function normalizeHost(value){const s=String(value||'').trim().toLowerCase().replace(/^\|\|/,'').replace(/\^.*$/,'').replace(/^https?:\/\//,'').replace(/\/.*$/,'').replace(/^\.+|\.+$/g,'');return /^[a-z0-9.-]+$/.test(s)&&s.includes('.')?s:'';}
function hostMatches(host,ruleHost){return host===ruleHost||host.endsWith('.'+ruleHost);}
function validCosmeticSelector(selector){const s=String(selector||'').trim();return Boolean(s&&s.length<=500&&!/[{}]/.test(s));}
function parseDomains(raw){const include=[],exclude=[];for(const x of String(raw||'').split('|')){const v=x.trim().toLowerCase();if(!v)continue;(v[0]==='~'?exclude:include).push(v.replace(/^~/,''));}return {include,exclude};}
function domainScopeMatches(scope,host){if(!scope)return true;if(scope.exclude.some(x=>hostMatches(host,x)))return false;return !scope.include.length||scope.include.some(x=>hostMatches(host,x));}
function escapeRegex(s){return s.replace(/[.\\+?()[\]|]/g,'\\$&').replace(/\*/g,'.*').replace(/\^/g,'(?:[^a-zA-Z0-9_.%-]|$)');}
function parseOptions(raw=''){const out={types:new Set(),notTypes:new Set(),thirdParty:null,domains:null,important:false,matchCase:false,removeParams:[],unsupported:[]};for(const tokenRaw of String(raw).split(',')){const token=tokenRaw.trim();if(!token)continue;const neg=token[0]==='~';const body=neg?token.slice(1):token;const parts=body.split('=');const name=parts.shift(),val=parts.join('=');if(TYPE_MAP[name])(neg?out.notTypes:out.types).add(TYPE_MAP[name]);else if(name==='third-party'||name==='3p')out.thirdParty=!neg;else if(name==='first-party'||name==='1p')out.thirdParty=neg;else if(name==='domain')out.domains=parseDomains(val);else if(name==='important')out.important=!neg;else if(name==='match-case')out.matchCase=!neg;else if(name==='removeparam'&&val)out.removeParams.push(val.slice(0,120));else out.unsupported.push(token);}return out;}
function compileNetworkRule(line,isAllow){let body=isAllow?line.slice(2):line,options='';const dollar=body.lastIndexOf('$');if(dollar>0){options=body.slice(dollar+1);body=body.slice(0,dollar);}if(!body)return null;const opt=parseOptions(options);let kind='pattern',host='',rx=null;if(body.startsWith('||')){const anchored=body.slice(2),cut=anchored.search(/[\/^?]/),hostToken=cut<0?anchored:anchored.slice(0,cut),rest=cut<0?'':anchored.slice(cut);host=normalizeHost(hostToken);if(host){if(!rest||rest==='^')kind='host';else{kind='hostpath';try{rx=new RegExp(escapeRegex(rest),opt.matchCase?'':'i');}catch{return null;}}}}if(kind==='pattern'){if(body.startsWith('/')&&body.endsWith('/')&&body.length<500){try{rx=new RegExp(body.slice(1,-1),opt.matchCase?'':'i');}catch{return null;}}else{let p=escapeRegex(body);if(body.startsWith('|'))p='^'+escapeRegex(body.slice(1));if(body.endsWith('|'))p=escapeRegex(body.slice(0,-1))+'$';try{rx=new RegExp(p,opt.matchCase?'':'i');}catch{return null;}}}return {allow:isAllow,raw:line,kind,host,rx,opt,effect:opt.removeParams.length?'removeparam':(opt.unsupported.length?'unsupported':'network')};}
function parseFilterRules(text){const block=[],allow=[],cosmetic=[],cosmeticAllow=[],network=[],removeParams=[];let ignored=0;for(const lineRaw of String(text||'').split(/\r?\n/).slice(0,100000)){const line=lineRaw.trim();if(!line||line.startsWith('!')||line.startsWith('['))continue;const exceptionAt=line.indexOf('#@#'),cosmeticAt=line.indexOf('##');if(exceptionAt>=0||cosmeticAt>=0){const at=exceptionAt>=0?exceptionAt:cosmeticAt,marker=exceptionAt>=0?'#@#':'##',selector=line.slice(at+marker.length).trim();if(selector.startsWith('+js(')||selector.startsWith('^script:has-text(')){ignored++;continue;}if(!validCosmeticSelector(selector)){ignored++;continue;}const domains=parseDomains(line.slice(0,at).replace(/,/g,'|')),entry={selector,domains};(exceptionAt>=0?cosmeticAllow:cosmetic).push(entry);continue;}const isAllow=line.startsWith('@@'),rule=compileNetworkRule(line,isAllow);if(!rule){ignored++;continue;}network.push(rule);if(rule.effect==='unsupported')ignored++;if(rule.effect==='network'&&rule.kind==='host'&&!rule.opt.types.size&&!rule.opt.notTypes.size&&!rule.opt.domains&&rule.opt.thirdParty===null)(isAllow?allow:block).push(rule.host);for(const p of rule.opt.removeParams)removeParams.push({param:p,domains:rule.opt.domains,host:rule.host||'',allow:isAllow,rule});}const exceptionSelectors=new Set(cosmeticAllow.map(x=>x.selector));const hostIndex=new Map(),patternRules=[];for(const r of network){if(r.effect!=='network')continue;if(r.kind==='host'){if(!hostIndex.has(r.host))hostIndex.set(r.host,[]);hostIndex.get(r.host).push(r);}else patternRules.push(r);}
return {block:[...new Set(block)].slice(0,50000),allow:[...new Set(allow)].slice(0,50000),network:network.slice(0,100000),cosmetic:[...new Set(cosmetic.map(x=>x.selector))].filter(x=>!exceptionSelectors.has(x)).slice(0,30000),cosmeticAllow:[...exceptionSelectors].slice(0,30000),cosmeticEntries:cosmetic.slice(0,30000),cosmeticAllowEntries:cosmeticAllow.slice(0,30000),removeParams:removeParams.slice(0,10000),ignored,_hostIndex:hostIndex,_patternRules:patternRules};}
function thirdPartyOf(rawUrl,topUrl){try{const a=new URL(rawUrl).hostname,b=new URL(topUrl).hostname;return !(hostMatches(a,b)||hostMatches(b,a));}catch{return false;}}
function networkRuleMatches(rule,rawUrl,ctx={}){let u;try{u=new URL(rawUrl);}catch{return false;}const host=u.hostname.toLowerCase();let topHost='';try{topHost=new URL(ctx.topUrl||'').hostname.toLowerCase();}catch{}if(rule.opt.types.size&&!rule.opt.types.has(ctx.resourceType))return false;if(rule.opt.notTypes.has(ctx.resourceType))return false;if(ctx.resourceType==='mainFrame'&&!rule.opt.types.has('mainFrame'))return false;if(rule.opt.thirdParty!==null&&thirdPartyOf(rawUrl,ctx.topUrl||rawUrl)!==rule.opt.thirdParty)return false;if(rule.opt.domains&&!domainScopeMatches(rule.opt.domains,topHost))return false;if(rule.kind==='host')return hostMatches(host,rule.host);if(rule.kind==='hostpath')return hostMatches(host,rule.host)&&rule.rx.test(u.pathname+u.search+u.hash);return rule.rx.test(rawUrl);}
function matchFilterRules(rawUrl,rules,ctx={}){let pool=(rules?.network||[]).filter(r=>r.effect==='network'||r.effect===undefined);if(rules?._hostIndex){let host='';try{host=new URL(rawUrl).hostname.toLowerCase();}catch{}const hostRules=[];const parts=host.split('.');for(let i=0;i<parts.length-1;i++){const rs=rules._hostIndex.get(parts.slice(i).join('.'));if(rs)hostRules.push(...rs);}pool=[...hostRules,...(rules._patternRules||[])];}const candidates=pool.filter(r=>networkRuleMatches(r,rawUrl,ctx));if(!candidates.length)return null;if(candidates.some(r=>!r.allow&&r.opt.important))return 'block';if(candidates.some(r=>r.allow))return 'allow';return candidates.some(r=>!r.allow)?'block':null;}
function cosmeticSelectorsForHost(host,rules){const h=String(host||'').toLowerCase(),allowed=new Set((rules?.cosmeticAllowEntries||[]).filter(e=>domainScopeMatches(e.domains,h)).map(e=>e.selector));return [...new Set((rules?.cosmeticEntries||[]).filter(e=>domainScopeMatches(e.domains,h)&&!allowed.has(e.selector)).map(e=>e.selector))].slice(0,10000);}
function removeParamEntryMatches(entry,rawUrl,ctx={}){if(entry?.rule){const rule=entry.rule;if(ctx.resourceType==='mainFrame'&&!rule.opt.types.size){const opt={...rule.opt,types:new Set(['mainFrame'])};return networkRuleMatches({...rule,opt},rawUrl,ctx);}return networkRuleMatches(rule,rawUrl,ctx);}let u;try{u=new URL(rawUrl);}catch{return false;}if(entry.host&&!hostMatches(u.hostname,entry.host))return false;let top='';try{top=new URL(ctx.topUrl||rawUrl).hostname;}catch{}if(entry.domains&&!domainScopeMatches(entry.domains,top))return false;return true;}
function applyRemoveParamRules(rawUrl,rules,ctx={}){let u;try{u=new URL(rawUrl);}catch{return rawUrl;}const entries=rules?.removeParams||[],allow=entries.filter(r=>r.allow);let changed=false;for(const r of entries){if(r.allow||!removeParamEntryMatches(r,rawUrl,ctx))continue;if(allow.some(a=>a.param===r.param&&removeParamEntryMatches(a,rawUrl,ctx)))continue;if(r.param.startsWith('/')&&r.param.endsWith('/')){let rx;try{rx=new RegExp(r.param.slice(1,-1));}catch{continue;}for(const k of [...u.searchParams.keys()])if(rx.test(k)){u.searchParams.delete(k);changed=true;}}else if(u.searchParams.has(r.param)){u.searchParams.delete(r.param);changed=true;}}return changed?u.toString():rawUrl;}
module.exports={parseFilterRules,matchFilterRules,normalizeHost,hostMatches,validCosmeticSelector,cosmeticSelectorsForHost,applyRemoveParamRules,parseOptions,domainScopeMatches};
